# fly.toml app configuration file generated for pomodoro-navi-db on 2025-01-25T20:19:44+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pomodoro-navi'
primary_region = 'nrt'

[build]
  dockerfile = './Dockerfile'

[env]
  PRIMARY_REGION = 'nrt'

[[mounts]]
  source = 'pg_data'
  destination = '/data'

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ['app']
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[metrics]]
  port = 9187
  path = '/metrics'
  https = false