# fly.toml app configuration file generated for pomodoro-navi-db on 2025-01-25T20:19:44+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pomodoro-navi'
primary_region = 'nrt'

[build]
  dockerfile = './Dockerfile'

[env]
  PRIMARY_REGION = 'nrt'

[[mounts]]
  source = 'pg_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 5432
  auto_start_machines = true

  [[services.ports]]
    port = 5432
    handlers = ['pg_tls']

  [services.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[services]]
  protocol = 'tcp'
  internal_port = 5433
  auto_start_machines = true

  [[services.ports]]
    port = 5433
    handlers = ['pg_tls']

  [services.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[checks]
  [checks.pg]
    port = 5432
    type = 'tcp'
    interval = '15s'
    timeout = '10s'

  [checks.role]
    port = 5433
    type = 'tcp'
    interval = '15s'
    timeout = '10s'

  [checks.vm]
    port = 3000
    type = 'http'
    interval = '15s'
    timeout = '10s'
    path = '/flycheck/vm'

[[metrics]]
  port = 9187
  path = '/metrics'
  https = false