default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV['POMODORO_NAVI_DATABASE_PASSWORD'] %>
  host: db
  port: 5432

development:
  <<: *default
  database: pomodoronavi_db_development

test:
  <<: *default
  database: pomodoronavi_db_test

production:
  <<: *default
  database: pomodoronavi_db_production
  url: <%= ENV['POMODORO_NAVI_DATABASE_URL'] %>