default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  sslmode: disable

development:
  <<: *default
  database: pomodoronavi_db_development

test:
  <<: *default
  database: pomodoronavi_db_test

production:
  <<: *default
  database: pomodoronavi_db_production